language: ruby
rvm:
  - 2.2.2
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
sudo: false # route your build to the container-based infrastructure for a faster build

before_install:
  - export TZ=Europe/London
  - openssl aes-256-cbc -K $encrypted_a1acb7ef69a3_key -iv $encrypted_a1acb7ef69a3_iv -in deploy_key.enc -out deploy_key -d

install: gem install jekyll html-proofer

script: jekyll build && htmlproofer ./_site

after_success:
  - eval "$(ssh-agent -s)" #start the ssh agent
  - chmod 600 deploy_key # this key should have push access
  - ssh-add deploy_key
  - git clone git@github.com:kausar007/kausar007.github.io.git deploy
  - cp -r _site/* deploy/
  - cd deploy
  - git config user.name "Kausar Mehmood"
  - git config user.email "kausar_doaba@yahoo.com"
  - git add .
  - git commit -m "Deploy by git commit $TRAVIS_COMMIT"
  - git push origin master
